apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nodeagent-cr
  name: nodeagent-cr
spec:
  selector:
    matchLabels:
      app: nodeagent-cr
  template:
    metadata:
      labels:
        app: nodeagent-cr
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - cp /opt/inferx/bin/na /na 2>/dev/null; exec /usr/local/bin/napodman-entrypoint.sh
        env:
        - name: NA_TYPE
          value: CR
        - name: STATESVC_ADDR
          value: http://statesvc:1237
        - name: IFERX_DISABLE_HELPERBUF
          value: "true"
        - name: INIT_CUDAHOSTALLOC
          value: "-1"
        - name: RUN_SERVICE
          value: NodeAgentAll
        - name: ENABLE_COREDUMP
          value: "false"
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: ALLOC_MEMORY
          valueFrom:
            resourceFieldRef:
              containerName: nodeagent
              divisor: "0"
              resource: limits.memory
        - name: ALLOC_MEMORY_2M
          valueFrom:
            resourceFieldRef:
              containerName: nodeagent
              divisor: "0"
              resource: limits.hugepages-2Mi
        - name: CACHE_MEMORY
          value: 25Gi
        - name: RESERVE_MEM_PERCENTAGE
          value: "10"
        - name: FLEXIBLE_MEM_PERCENTAGE
          value: "10"
        - name: CONTEXT_COUNT
          value: "1"
        - name: ALLOC_CPU
          valueFrom:
            resourceFieldRef:
              containerName: nodeagent
              divisor: "0"
              resource: limits.cpu
        image: napodman-test:latest
        imagePullPolicy: IfNotPresent
        name: nodeagent
        resources:
          limits:
            cpu: "20"
            memory: 160Gi
          requests:
            cpu: "1"
            memory: 30Gi
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
            - IPC_LOCK
            - SYS_RAWIO
          privileged: true
          runAsGroup: 0
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/udev
          name: run-udev
        - mountPath: /opt/inferx
          name: opt-inferx
        - mountPath: /var/run/docker/runtime-runc/moby/
          name: docker-runtime
        - mountPath: /home/brad/mnt
          name: docker-mnt
        - mountPath: /var/lib/docker
          name: dind
      dnsPolicy: ClusterFirst
      hostPID: true
      nodeSelector:
        inferx_nodeType: inferx_file
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /run/udev
          type: ""
        name: run-udev
      - hostPath:
          path: /opt/inferx/
          type: ""
        name: opt-inferx
      - hostPath:
          path: /var/run/docker/runtime-runc/moby/
          type: ""
        name: docker-runtime
      - hostPath:
          path: /home/brad/mnt
          type: ""
        name: docker-mnt
      - hostPath:
          path: /opt/inferx/dind
          type: ""
        name: dind
