apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.13
          volumeMounts:
            - name: etcd-data
              mountPath: /opt/inferx/data/etcd
          command: [ "etcd" ]
          args:
            - "--name=etcd-00"
            - "--data-dir=/opt/inferx/data/etcd"
            - "--advertise-client-urls=http://localhost:2379"
            - "--listen-client-urls=http://0.0.0.0:2379"
            - "--initial-advertise-peer-urls=http://localhost:2380"
            - "--listen-peer-urls=http://0.0.0.0:2380"
            - "--initial-cluster=etcd-00=http://localhost:2380"
      volumes:
        - name: etcd-data
          hostPath:
            path: /opt/inferx/data/etcd
            type: DirectoryOrCreate
