apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      hostPID: true
      containers:
        - name: gateway
          image: inferx/inferx_platform:v0.1.4
          imagePullPolicy: IfNotPresent
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP          
          - name: RUN_SERVICE
            value: "Gateway"
          - name: STATESVC_ADDR
            value: "http://statesvc:1237"
          volumeMounts:
            - mountPath: /opt/inferx/log
              name: opt-inferx-log
          command: ["./svc", "/opt/inferx/config/node.json"]
      volumes:
        - name: opt-inferx-log
          hostPath:
            path: /opt/inferx/log      
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 31501  

