apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      hostPID: true
      containers:
        - name: scheduler
          image: inferx/inferx_platform:v0.1.4
          imagePullPolicy: IfNotPresent
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP          
          - name: RUN_SERVICE
            value: "Scheduler"
          - name: STATESVC_ADDR
            value: "http://statesvc:1237"
          - name: ETCD_ADDRS
            value: "http://localhost:2379"
          - name: SCHEDULER_PORT
            value: "1238"
          volumeMounts:
            - mountPath: /opt/inferx/log
              name: opt-inferx-log
          command: ["./svc", "/opt/inferx/config/node.json"]
      volumes:
        - name: opt-inferx-log
          hostPath:
            path: /opt/inferx/log      
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler
spec:
  type: NodePort
  selector:
    app: scheduler
  ports:
    - name: http
      port: 1238
      targetPort: 1238
