apiVersion: apps/v1
kind: Deployment
metadata:
  name: statesvc
  labels:
    app: statesvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: statesvc
  template:
    metadata:
      labels:
        app: statesvc
    spec:
      hostPID: true
      containers:
        - name: statesvc
          image: inferx/inferx_one:v0.1.1
          imagePullPolicy: IfNotPresent
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP          
          - name: RUN_SERVICE
            value: "StateSvc"
          - name: CACHE_MEMORY
            value: 20Gi
          volumeMounts:
            - mountPath: /opt/inferx/
              name: opt-inferx
          command: ["./onenode", "/opt/inferx/config/node.json"]
      volumes:
        - name: opt-inferx
          hostPath:
            path: /opt/inferx/       
---
apiVersion: v1
kind: Service
metadata:
  name: statesvc
spec:
  type: NodePort
  selector:
    app: statesvc
  ports:
    - name: http
      port: 1237
      targetPort: 1237
