{
 "title": "InferX",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "gpu utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * sum(usedGPU) / sum(totalGPU)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cs_latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(funccallCsTtft_bucket[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, rate(funccallCsTtft_bucket[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.50, rate(funccallCsTtft_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total GPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "totalGPU", "legendFormat": "__auto" },
    { "expr": "usedGPU", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cold start ttft",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "funccallCsTtft_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "funccall_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "rate(funccallcnt_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "query count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "funccallTtft_count", "legendFormat": "__auto" }
   ]
  }
 ]
}